# Generated by Django 5.2.11 on 2026-02-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0038_add_channel_sort_order'),
    ]

    def set_default_sort(apps, schema_editor):
        ChannelGroup = apps.get_model('dispatcharr_channels', 'ChannelGroup')
        ChannelGroup.objects.filter(sort_mode='manual').update(sort_mode='auto', sort_field='name_asc')

    operations = [
        migrations.AlterField(
            model_name='channelgroup',
            name='sort_field',
            field=models.CharField(blank=True, choices=[('channel_number_asc', 'Channel Number (Ascending)'), ('channel_number_desc', 'Channel Number (Descending)'), ('name_asc', 'Name (A-Z)'), ('name_desc', 'Name (Z-A)')], default='name_asc', help_text="Field to sort by when sort_mode is 'auto'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='sort_mode',
            field=models.CharField(choices=[('manual', 'Manual Order'), ('auto', 'Auto Sort')], default='auto', help_text='How channels in this group are ordered', max_length=20),
        ),
        migrations.RunPython(set_default_sort),
    ]
