# Generated by Django 5.2.11 on 2026-02-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtream', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelgroupxtreamaccount',
            new_name='xtream_chan_xtream__f0ae19_idx',
            old_name='xtream_chan_xtream__e984cc_idx',
        ),
    ]
